server:
  port: 8002

# MyBatis
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.cloud
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations:  classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: provider-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://             # 数据库名称
    username:
    password:
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #自定义显示名称
    instance-id: ${spring.application.name}:${server.port}
    #是否显示真实地址
    prefer-ip-address: true

info:
  app.name: ${spring.application.name}
  company.name: ccs