server:
  port: 8100


spring:
  application:
    name: cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #自定义显示名称
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #是否显示真实地址
    prefer-ip-address: true

zuul:
  #忽略真实服务名如果要忽略全部使用*否则指定要忽略的如:ignored-services: provider-user-a
  ignored-services: "*"
  routes:
    provider-a:
      serviceId: provider-user-a
      path: /my-provider/**
  #设置统一公共前缀
  prefix: /cloud

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app.name: ${spring.application.name}
  company.name: ccs