server:
  port: 9001

spring:
  application:
    name: zipkin-consumer-1
  zipkin:
    base-url: http://localhost:2001
    #开启zipkin
    enabled: true
  sleuth:
    sampler:
      #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，
      #如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
      probability: 1

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka

feign:
  hystrix:
    #开启服务降级
    enabled: true
