server:
  port: 1001
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wujid/cloud-demo-config-2.git
          username:
          password: